### ISSUE TITLE
Building on windows using visual studio

### ISSUE THREAD

**Issue by MostafaNanticock** [AlexandreRouma/LimeOS#1]
_linker.ld_ causes the compiler to output the following error
`Error	LNK1107	invalid or corrupt file: cannot read at 0x486	LimeOS  linker.ld`

**Comment by AlexandreRouma** [comment]
Hi, 

Sorry, this OS can only be built on WSL or Linux using GCC or Clang.
MSVC isn't supported as it's not a cross compiler.
